import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Search, ShoppingBag, Heart, Menu, X, ArrowRight, Star, Truck, ShieldCheck, RotateCcw, Minus, Plus, Trash2 } from 'lucide-react';
import Checkout from './Checkout';
import { loadStore, saveStore } from './store';
import './styles.css';

function App(){
 const initial=loadStore();
 const [products]=useState(initial.products); const [cart,setCart]=useState(initial.cart||[]); const [liked,setLiked]=useState(initial.wishlist||[]);
 const [query,setQuery]=useState(''); const [category,setCategory]=useState('All'); const [open,setOpen]=useState(false); const [cartOpen,setCartOpen]=useState(false); const [checkout,setCheckout]=useState(false);
 const filtered=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase())),[products,category,query]);
 const persist=(nextCart=cart,nextLiked=liked)=>saveStore({...loadStore(),cart:nextCart,wishlist:nextLiked});
 const add=p=>{const next=cart.some(i=>i.id===p.id)?cart.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...cart,{...p,qty:1}];setCart(next);persist(next);setCartOpen(true)};
 const change=(id,delta)=>{const next=cart.map(i=>i.id===id?{...i,qty:Math.max(0,i.qty+delta)}:i).filter(i=>i.qty>0);setCart(next);persist(next)};
 const remove=id=>{const next=cart.filter(i=>i.id!==id);setCart(next);persist(next)};
 const toggleLike=id=>{const next=liked.includes(id)?liked.filter(x=>x!==id):[...liked,id];setLiked(next);persist(cart,next)};
 const total=cart.reduce((s,p)=>s+p.price*p.qty,0); const count=cart.reduce((s,p)=>s+p.qty,0);
 if(checkout) return <Checkout cart={cart} onBack={()=>setCheckout(false)} onComplete={()=>{setCart([]);setCheckout(false);setCartOpen(false)}}/>;
 return <div>
  <div className="announcement">Free shipping on orders over $50 <span>•</span> New drops every week</div>
  <header><div className="nav wrap"><button className="icon mobile" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div className="logo">DROP<span>FORGE</span></div><nav className={open?'show':''}><a href="#shop">Shop</a><a href="#deals">Deals</a><a href="#why">Why DropForge</a><a href="#footer">Contact</a></nav><div className="actions"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products..."/></div><button className="icon" onClick={()=>setCartOpen(true)}><ShoppingBag/><b>{count}</b></button></div></div></header>
  <main>
   <section className="hero wrap"><div><p className="eyebrow">CURATED. AFFORDABLE. DELIVERED.</p><h1>Find your next <em>favorite.</em></h1><p className="hero-copy">Trending products, honest prices and a smooth checkout. Discover useful things you’ll actually want to keep.</p><div className="hero-buttons"><a className="btn dark" href="#shop">Shop the collection <ArrowRight size={17}/></a><a className="text-btn" href="#deals">See today's deals</a></div><div className="trust"><span><Star/> 4.8/5 average rating</span><span><Truck/> Fast tracked delivery</span></div></div><div className="hero-card"><img src="https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1100&q=85"/><div className="float-card"><small>DROP OF THE WEEK</small><strong>Smart essentials</strong><span>Save up to 40%</span></div></div></section>
   <section id="shop" className="section wrap"><div className="section-head"><div><p className="eyebrow">SHOP</p><h2>Made for your everyday.</h2></div><div className="filters">{['All','Tech','Home','Fashion'].map(c=><button className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div></div><div className="grid">{filtered.map(p=><article className="product" key={p.id}><div className="product-image"><img src={p.image}/><span>{p.badge}</span><button className="heart" onClick={()=>toggleLike(p.id)}><Heart fill={liked.includes(p.id)?'currentColor':'none'}/></button></div><div className="product-info"><div className="rating"><Star fill="currentColor" size={14}/> {p.rating}</div><h3>{p.name}</h3><p>{p.category} · {p.stock} in stock</p><div className="price"><strong>${p.price.toFixed(2)}</strong><del>${p.old.toFixed(2)}</del></div><button className="add" onClick={()=>add(p)}>Add to cart</button></div></article>)}</div>{filtered.length===0&&<div className="no-results">No products found. Try another search.</div>}</section>
   <section id="deals" className="deal wrap"><div><p className="eyebrow">LIMITED-TIME DROP</p><h2>Better finds.<br/><em>Better prices.</em></h2><p>Take 20% off your first order with code <b>FORGE20</b>.</p><a className="btn light" href="#shop">Shop deals <ArrowRight size={17}/></a></div><div className="deal-stat"><strong>20%</strong><span>OFF FIRST ORDER</span></div></section>
   <section id="why" className="section wrap"><div className="center"><p className="eyebrow">THE DROP FORGE STANDARD</p><h2>Shopping without the guesswork.</h2></div><div className="perks"><div><Truck/><h3>Tracked delivery</h3><p>Clear delivery updates from checkout to doorstep.</p></div><div><ShieldCheck/><h3>Secure checkout</h3><p>Your payment details stay protected at every step.</p></div><div><RotateCcw/><h3>Simple returns</h3><p>Changed your mind? Our support team has your back.</p></div></div></section>
  </main>
  <footer id="footer"><div className="wrap footer-grid"><div><div className="logo">DROP<span>FORGE</span></div><p>Useful finds. Better prices. No clutter.</p></div><div><h4>Shop</h4><a href="#shop">All products</a><a href="#shop">Tech</a><a href="#shop">Home</a><a href="#shop">Fashion</a></div><div><h4>Help</h4><a href="#why">Shipping</a><a href="#why">Returns</a><a href="#footer">Track order</a><a href="#footer">Contact</a></div><div><h4>Stay in the loop</h4><p>Get new drops and private offers.</p><div className="email"><input placeholder="Your email"/><button>→</button></div></div></div><div className="copyright wrap">© 2026 DropForge. All rights reserved.</div></footer>
  {cartOpen&&<div className="overlay" onClick={()=>setCartOpen(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><h2>Your cart</h2><button className="icon" onClick={()=>setCartOpen(false)}><X/></button></div>{cart.length===0?<div className="empty"><ShoppingBag size={38}/><h3>Your cart is empty</h3><p>Find something you love and add it here.</p></div>:<><div className="cart-items">{cart.map(p=><div className="cart-item" key={p.id}><img src={p.image}/><div className="cart-item-main"><strong>{p.name}</strong><span>${p.price.toFixed(2)}</span><div className="qty"><button onClick={()=>change(p.id,-1)}><Minus size={13}/></button><b>{p.qty}</b><button onClick={()=>change(p.id,1)}><Plus size={13}/></button><button className="remove" onClick={()=>remove(p.id)}><Trash2 size={14}/></button></div></div></div>)}</div><div className="checkout"><div><span>Subtotal</span><strong>${total.toFixed(2)}</strong></div><button className="btn dark full" onClick={()=>setCheckout(true)}>Checkout <ArrowRight size={17}/></button><small>Taxes and shipping calculated at checkout.</small></div></>}</aside></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
